version: '3'
services:
  teamwiki-mysql:
    image: mysql
    container_name: teamwiki-mysql
    volumes:
      - teamwiki-mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=team_wiki

  teamwiki-redis:
    image: redis
    container_name: teamwiki-redis

  teamwiki:
    build: .
    container_name: teamwiki
    ports:
      - 8081:8081
    volumes:
      - teamwiki-data:/var/data/teamwiki
      - teamwiki-log:/var/log/teamwiki
    links:
      - teamwiki-mysql
      - teamwiki-redis
    depends_on:
      - teamwiki-mysql
      - teamwiki-redis

  teamwiki-web:
    image: teamwiki-web
    container_name: teamwiki-web
    ports:
      - 8080:8080
    links:
      - teamwiki
    depends_on:
      - teamwiki