/*
 * This file is generated by jOOQ.
 */
package cn.edu.nju.teamwiki.jooq;


import cn.edu.nju.teamwiki.jooq.tables.Knowledge;
import cn.edu.nju.teamwiki.jooq.tables.Role;
import cn.edu.nju.teamwiki.jooq.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in team_wiki
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * A table to contain all knowledge
     */
    public static final Knowledge KNOWLEDGE = Knowledge.KNOWLEDGE;

    /**
     * A table to contain all roles
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * A table to contain all the users
     */
    public static final User USER = User.USER;
}
