/*
 * This file is generated by jOOQ.
 */
package cn.edu.nju.teamwiki.jooq;


import cn.edu.nju.teamwiki.jooq.tables.Category;
import cn.edu.nju.teamwiki.jooq.tables.Document;
import cn.edu.nju.teamwiki.jooq.tables.DocumentActivities;
import cn.edu.nju.teamwiki.jooq.tables.Knowledge;
import cn.edu.nju.teamwiki.jooq.tables.Portal;
import cn.edu.nju.teamwiki.jooq.tables.Role;
import cn.edu.nju.teamwiki.jooq.tables.Share;
import cn.edu.nju.teamwiki.jooq.tables.Source;
import cn.edu.nju.teamwiki.jooq.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamWiki extends SchemaImpl {

    private static final long serialVersionUID = -1044772846;

    /**
     * The reference instance of <code>team_wiki</code>
     */
    public static final TeamWiki TEAM_WIKI = new TeamWiki();

    /**
     * The table <code>team_wiki.category</code>.
     */
    public final Category CATEGORY = cn.edu.nju.teamwiki.jooq.tables.Category.CATEGORY;

    /**
     * The table <code>team_wiki.document</code>.
     */
    public final Document DOCUMENT = cn.edu.nju.teamwiki.jooq.tables.Document.DOCUMENT;

    /**
     * The table <code>team_wiki.document_activities</code>.
     */
    public final DocumentActivities DOCUMENT_ACTIVITIES = cn.edu.nju.teamwiki.jooq.tables.DocumentActivities.DOCUMENT_ACTIVITIES;

    /**
     * A table to contain all knowledge
     */
    public final Knowledge KNOWLEDGE = cn.edu.nju.teamwiki.jooq.tables.Knowledge.KNOWLEDGE;

    /**
     * The table <code>team_wiki.portal</code>.
     */
    public final Portal PORTAL = cn.edu.nju.teamwiki.jooq.tables.Portal.PORTAL;

    /**
     * A table to contain all roles
     */
    public final Role ROLE = cn.edu.nju.teamwiki.jooq.tables.Role.ROLE;

    /**
     * The table <code>team_wiki.share</code>.
     */
    public final Share SHARE = cn.edu.nju.teamwiki.jooq.tables.Share.SHARE;

    /**
     * The table <code>team_wiki.source</code>.
     */
    public final Source SOURCE = cn.edu.nju.teamwiki.jooq.tables.Source.SOURCE;

    /**
     * A table to contain all the users
     */
    public final User USER = cn.edu.nju.teamwiki.jooq.tables.User.USER;

    /**
     * No further instances allowed
     */
    private TeamWiki() {
        super("team_wiki", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Category.CATEGORY,
            Document.DOCUMENT,
            DocumentActivities.DOCUMENT_ACTIVITIES,
            Knowledge.KNOWLEDGE,
            Portal.PORTAL,
            Role.ROLE,
            Share.SHARE,
            Source.SOURCE,
            User.USER);
    }
}
