/*
 * This file is generated by jOOQ.
 */
package cn.edu.nju.teamwiki.jooq;


import cn.edu.nju.teamwiki.jooq.tables.Knowledge;
import cn.edu.nju.teamwiki.jooq.tables.Role;
import cn.edu.nju.teamwiki.jooq.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamWiki extends SchemaImpl {

    private static final long serialVersionUID = -1664886172;

    /**
     * The reference instance of <code>team_wiki</code>
     */
    public static final TeamWiki TEAM_WIKI = new TeamWiki();

    /**
     * A table to contain all knowledge
     */
    public final Knowledge KNOWLEDGE = cn.edu.nju.teamwiki.jooq.tables.Knowledge.KNOWLEDGE;

    /**
     * A table to contain all roles
     */
    public final Role ROLE = cn.edu.nju.teamwiki.jooq.tables.Role.ROLE;

    /**
     * A table to contain all the users
     */
    public final User USER = cn.edu.nju.teamwiki.jooq.tables.User.USER;

    /**
     * No further instances allowed
     */
    private TeamWiki() {
        super("team_wiki", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Knowledge.KNOWLEDGE,
            Role.ROLE,
            User.USER);
    }
}
