/*
 * This file is generated by jOOQ.
 */
package cn.edu.nju.teamwiki.jooq.tables.records;


import cn.edu.nju.teamwiki.jooq.tables.Knowledge;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * A table to contain all knowledge
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KnowledgeRecord extends UpdatableRecordImpl<KnowledgeRecord> implements Record5<Integer, String, Boolean, Integer, Integer> {

    private static final long serialVersionUID = 449032027;

    /**
     * Setter for <code>team_wiki.knowledge.k_id</code>.
     */
    public void setKId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>team_wiki.knowledge.k_id</code>.
     */
    public Integer getKId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>team_wiki.knowledge.k_name</code>.
     */
    public void setKName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>team_wiki.knowledge.k_name</code>.
     */
    public String getKName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>team_wiki.knowledge.predefined</code>.
     */
    public void setPredefined(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>team_wiki.knowledge.predefined</code>.
     */
    public Boolean getPredefined() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>team_wiki.knowledge.category</code>.
     */
    public void setCategory(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>team_wiki.knowledge.category</code>.
     */
    public Integer getCategory() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>team_wiki.knowledge.creator</code>.
     */
    public void setCreator(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>team_wiki.knowledge.creator</code>.
     */
    public Integer getCreator() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Boolean, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, Boolean, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Knowledge.KNOWLEDGE.K_ID;
    }

    @Override
    public Field<String> field2() {
        return Knowledge.KNOWLEDGE.K_NAME;
    }

    @Override
    public Field<Boolean> field3() {
        return Knowledge.KNOWLEDGE.PREDEFINED;
    }

    @Override
    public Field<Integer> field4() {
        return Knowledge.KNOWLEDGE.CATEGORY;
    }

    @Override
    public Field<Integer> field5() {
        return Knowledge.KNOWLEDGE.CREATOR;
    }

    @Override
    public Integer component1() {
        return getKId();
    }

    @Override
    public String component2() {
        return getKName();
    }

    @Override
    public Boolean component3() {
        return getPredefined();
    }

    @Override
    public Integer component4() {
        return getCategory();
    }

    @Override
    public Integer component5() {
        return getCreator();
    }

    @Override
    public Integer value1() {
        return getKId();
    }

    @Override
    public String value2() {
        return getKName();
    }

    @Override
    public Boolean value3() {
        return getPredefined();
    }

    @Override
    public Integer value4() {
        return getCategory();
    }

    @Override
    public Integer value5() {
        return getCreator();
    }

    @Override
    public KnowledgeRecord value1(Integer value) {
        setKId(value);
        return this;
    }

    @Override
    public KnowledgeRecord value2(String value) {
        setKName(value);
        return this;
    }

    @Override
    public KnowledgeRecord value3(Boolean value) {
        setPredefined(value);
        return this;
    }

    @Override
    public KnowledgeRecord value4(Integer value) {
        setCategory(value);
        return this;
    }

    @Override
    public KnowledgeRecord value5(Integer value) {
        setCreator(value);
        return this;
    }

    @Override
    public KnowledgeRecord values(Integer value1, String value2, Boolean value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KnowledgeRecord
     */
    public KnowledgeRecord() {
        super(Knowledge.KNOWLEDGE);
    }

    /**
     * Create a detached, initialised KnowledgeRecord
     */
    public KnowledgeRecord(Integer kId, String kName, Boolean predefined, Integer category, Integer creator) {
        super(Knowledge.KNOWLEDGE);

        set(0, kId);
        set(1, kName);
        set(2, predefined);
        set(3, category);
        set(4, creator);
    }
}
