/*
 * This file is generated by jOOQ.
 */
package cn.edu.nju.teamwiki.jooq.tables.records;


import cn.edu.nju.teamwiki.jooq.tables.Portal;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PortalRecord extends UpdatableRecordImpl<PortalRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = -973476700;

    /**
     * Setter for <code>team_wiki.portal.portal_id</code>.
     */
    public void setPortalId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>team_wiki.portal.portal_id</code>.
     */
    public Integer getPortalId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>team_wiki.portal.portal_name</code>.
     */
    public void setPortalName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>team_wiki.portal.portal_name</code>.
     */
    public String getPortalName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>team_wiki.portal.portal_link</code>.
     */
    public void setPortalLink(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>team_wiki.portal.portal_link</code>.
     */
    public String getPortalLink() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Portal.PORTAL.PORTAL_ID;
    }

    @Override
    public Field<String> field2() {
        return Portal.PORTAL.PORTAL_NAME;
    }

    @Override
    public Field<String> field3() {
        return Portal.PORTAL.PORTAL_LINK;
    }

    @Override
    public Integer component1() {
        return getPortalId();
    }

    @Override
    public String component2() {
        return getPortalName();
    }

    @Override
    public String component3() {
        return getPortalLink();
    }

    @Override
    public Integer value1() {
        return getPortalId();
    }

    @Override
    public String value2() {
        return getPortalName();
    }

    @Override
    public String value3() {
        return getPortalLink();
    }

    @Override
    public PortalRecord value1(Integer value) {
        setPortalId(value);
        return this;
    }

    @Override
    public PortalRecord value2(String value) {
        setPortalName(value);
        return this;
    }

    @Override
    public PortalRecord value3(String value) {
        setPortalLink(value);
        return this;
    }

    @Override
    public PortalRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PortalRecord
     */
    public PortalRecord() {
        super(Portal.PORTAL);
    }

    /**
     * Create a detached, initialised PortalRecord
     */
    public PortalRecord(Integer portalId, String portalName, String portalLink) {
        super(Portal.PORTAL);

        set(0, portalId);
        set(1, portalName);
        set(2, portalLink);
    }
}
