/*
 * This file is generated by jOOQ.
 */
package cn.edu.nju.teamwiki.jooq.tables.records;


import cn.edu.nju.teamwiki.jooq.tables.User;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * A table to contain all the users
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record8<Integer, String, String, String, Integer, String, String, String> {

    private static final long serialVersionUID = 1054536986;

    /**
     * Setter for <code>team_wiki.user.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>team_wiki.user.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>team_wiki.user.email</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>team_wiki.user.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>team_wiki.user.username</code>.
     */
    public void setUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>team_wiki.user.username</code>.
     */
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>team_wiki.user.password</code>.
     */
    public void setPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>team_wiki.user.password</code>.
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>team_wiki.user.role</code>.
     */
    public void setRole(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>team_wiki.user.role</code>.
     */
    public Integer getRole() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>team_wiki.user.avatar</code>.
     */
    public void setAvatar(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>team_wiki.user.avatar</code>.
     */
    public String getAvatar() {
        return (String) get(5);
    }

    /**
     * Setter for <code>team_wiki.user.phone</code>.
     */
    public void setPhone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>team_wiki.user.phone</code>.
     */
    public String getPhone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>team_wiki.user.introduction</code>.
     */
    public void setIntroduction(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>team_wiki.user.introduction</code>.
     */
    public String getIntroduction() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, String, Integer, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, String, Integer, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return User.USER.USER_ID;
    }

    @Override
    public Field<String> field2() {
        return User.USER.EMAIL;
    }

    @Override
    public Field<String> field3() {
        return User.USER.USERNAME;
    }

    @Override
    public Field<String> field4() {
        return User.USER.PASSWORD;
    }

    @Override
    public Field<Integer> field5() {
        return User.USER.ROLE;
    }

    @Override
    public Field<String> field6() {
        return User.USER.AVATAR;
    }

    @Override
    public Field<String> field7() {
        return User.USER.PHONE;
    }

    @Override
    public Field<String> field8() {
        return User.USER.INTRODUCTION;
    }

    @Override
    public Integer component1() {
        return getUserId();
    }

    @Override
    public String component2() {
        return getEmail();
    }

    @Override
    public String component3() {
        return getUsername();
    }

    @Override
    public String component4() {
        return getPassword();
    }

    @Override
    public Integer component5() {
        return getRole();
    }

    @Override
    public String component6() {
        return getAvatar();
    }

    @Override
    public String component7() {
        return getPhone();
    }

    @Override
    public String component8() {
        return getIntroduction();
    }

    @Override
    public Integer value1() {
        return getUserId();
    }

    @Override
    public String value2() {
        return getEmail();
    }

    @Override
    public String value3() {
        return getUsername();
    }

    @Override
    public String value4() {
        return getPassword();
    }

    @Override
    public Integer value5() {
        return getRole();
    }

    @Override
    public String value6() {
        return getAvatar();
    }

    @Override
    public String value7() {
        return getPhone();
    }

    @Override
    public String value8() {
        return getIntroduction();
    }

    @Override
    public UserRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UserRecord value3(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public UserRecord value4(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserRecord value5(Integer value) {
        setRole(value);
        return this;
    }

    @Override
    public UserRecord value6(String value) {
        setAvatar(value);
        return this;
    }

    @Override
    public UserRecord value7(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public UserRecord value8(String value) {
        setIntroduction(value);
        return this;
    }

    @Override
    public UserRecord values(Integer value1, String value2, String value3, String value4, Integer value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Integer userId, String email, String username, String password, Integer role, String avatar, String phone, String introduction) {
        super(User.USER);

        set(0, userId);
        set(1, email);
        set(2, username);
        set(3, password);
        set(4, role);
        set(5, avatar);
        set(6, phone);
        set(7, introduction);
    }
}
