/*
 * This file is generated by jOOQ.
 */
package cn.edu.nju.teamwiki.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Announcement implements Serializable {

    private static final long serialVersionUID = -1868548362;

    private Integer       announcementId;
    private String        content;
    private LocalDateTime publishTime;

    public Announcement() {}

    public Announcement(Announcement value) {
        this.announcementId = value.announcementId;
        this.content = value.content;
        this.publishTime = value.publishTime;
    }

    public Announcement(
        Integer       announcementId,
        String        content,
        LocalDateTime publishTime
    ) {
        this.announcementId = announcementId;
        this.content = content;
        this.publishTime = publishTime;
    }

    public Integer getAnnouncementId() {
        return this.announcementId;
    }

    public void setAnnouncementId(Integer announcementId) {
        this.announcementId = announcementId;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public LocalDateTime getPublishTime() {
        return this.publishTime;
    }

    public void setPublishTime(LocalDateTime publishTime) {
        this.publishTime = publishTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Announcement (");

        sb.append(announcementId);
        sb.append(", ").append(content);
        sb.append(", ").append(publishTime);

        sb.append(")");
        return sb.toString();
    }
}
