/*
 * This file is generated by jOOQ.
 */
package cn.edu.nju.teamwiki.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DocumentActivities implements Serializable {

    private static final long serialVersionUID = -1051893008;

    private String        documentId;
    private Integer       userId;
    private String        action;
    private LocalDateTime time;

    public DocumentActivities() {}

    public DocumentActivities(DocumentActivities value) {
        this.documentId = value.documentId;
        this.userId = value.userId;
        this.action = value.action;
        this.time = value.time;
    }

    public DocumentActivities(
        String        documentId,
        Integer       userId,
        String        action,
        LocalDateTime time
    ) {
        this.documentId = documentId;
        this.userId = userId;
        this.action = action;
        this.time = time;
    }

    public String getDocumentId() {
        return this.documentId;
    }

    public void setDocumentId(String documentId) {
        this.documentId = documentId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getAction() {
        return this.action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public LocalDateTime getTime() {
        return this.time;
    }

    public void setTime(LocalDateTime time) {
        this.time = time;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DocumentActivities (");

        sb.append(documentId);
        sb.append(", ").append(userId);
        sb.append(", ").append(action);
        sb.append(", ").append(time);

        sb.append(")");
        return sb.toString();
    }
}
