/*
 * This file is generated by jOOQ.
 */
package cn.edu.nju.teamwiki.jooq.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Document implements Serializable {

    private static final long serialVersionUID = 1781374130;

    private String dId;
    private String dName;
    private Integer uploader;
    private LocalDateTime uploadedTime;
    private LocalDateTime modifiedTime;
    private Integer sourceType;
    private Integer sourceId;
    private String url;

    public Document() {
    }

    public Document(Document value) {
        this.dId = value.dId;
        this.dName = value.dName;
        this.uploader = value.uploader;
        this.uploadedTime = value.uploadedTime;
        this.modifiedTime = value.modifiedTime;
        this.sourceType = value.sourceType;
        this.sourceId = value.sourceId;
        this.url = value.url;
    }

    public Document(
            String dId,
            String dName,
            Integer uploader,
            LocalDateTime uploadedTime,
            LocalDateTime modifiedTime,
            Integer sourceType,
            Integer sourceId,
            String url
    ) {
        this.dId = dId;
        this.dName = dName;
        this.uploader = uploader;
        this.uploadedTime = uploadedTime;
        this.modifiedTime = modifiedTime;
        this.sourceType = sourceType;
        this.sourceId = sourceId;
        this.url = url;
    }

    public String getDId() {
        return this.dId;
    }

    public void setDId(String dId) {
        this.dId = dId;
    }

    public String getDName() {
        return this.dName;
    }

    public void setDName(String dName) {
        this.dName = dName;
    }

    public Integer getUploader() {
        return this.uploader;
    }

    public void setUploader(Integer uploader) {
        this.uploader = uploader;
    }

    public LocalDateTime getUploadedTime() {
        return this.uploadedTime;
    }

    public void setUploadedTime(LocalDateTime uploadedTime) {
        this.uploadedTime = uploadedTime;
    }

    public LocalDateTime getModifiedTime() {
        return this.modifiedTime;
    }

    public void setModifiedTime(LocalDateTime modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    public Integer getSourceType() {
        return this.sourceType;
    }

    public void setSourceType(Integer sourceType) {
        this.sourceType = sourceType;
    }

    public Integer getSourceId() {
        return this.sourceId;
    }

    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Document (");

        sb.append(dId);
        sb.append(", ").append(dName);
        sb.append(", ").append(uploader);
        sb.append(", ").append(uploadedTime);
        sb.append(", ").append(modifiedTime);
        sb.append(", ").append(sourceType);
        sb.append(", ").append(sourceId);
        sb.append(", ").append(url);

        sb.append(")");
        return sb.toString();
    }
}
