/*
 * This file is generated by jOOQ.
 */
package cn.edu.nju.teamwiki.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * A table to contain all knowledge
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Knowledge implements Serializable {

    private static final long serialVersionUID = -2109330991;

    private Integer       kId;
    private String        kName;
    private String        storagePath;
    private Integer       uploader;
    private LocalDateTime uploadTime;

    public Knowledge() {}

    public Knowledge(Knowledge value) {
        this.kId = value.kId;
        this.kName = value.kName;
        this.storagePath = value.storagePath;
        this.uploader = value.uploader;
        this.uploadTime = value.uploadTime;
    }

    public Knowledge(
        Integer       kId,
        String        kName,
        String        storagePath,
        Integer       uploader,
        LocalDateTime uploadTime
    ) {
        this.kId = kId;
        this.kName = kName;
        this.storagePath = storagePath;
        this.uploader = uploader;
        this.uploadTime = uploadTime;
    }

    public Integer getKId() {
        return this.kId;
    }

    public void setKId(Integer kId) {
        this.kId = kId;
    }

    public String getKName() {
        return this.kName;
    }

    public void setKName(String kName) {
        this.kName = kName;
    }

    public String getStoragePath() {
        return this.storagePath;
    }

    public void setStoragePath(String storagePath) {
        this.storagePath = storagePath;
    }

    public Integer getUploader() {
        return this.uploader;
    }

    public void setUploader(Integer uploader) {
        this.uploader = uploader;
    }

    public LocalDateTime getUploadTime() {
        return this.uploadTime;
    }

    public void setUploadTime(LocalDateTime uploadTime) {
        this.uploadTime = uploadTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Knowledge (");

        sb.append(kId);
        sb.append(", ").append(kName);
        sb.append(", ").append(storagePath);
        sb.append(", ").append(uploader);
        sb.append(", ").append(uploadTime);

        sb.append(")");
        return sb.toString();
    }
}
