/*
 * This file is generated by jOOQ.
 */
package cn.edu.nju.teamwiki.jooq.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Portal implements Serializable {

    private static final long serialVersionUID = 1898150752;

    private Integer portalId;
    private String portalName;
    private String portalLink;

    public Portal() {
    }

    public Portal(Portal value) {
        this.portalId = value.portalId;
        this.portalName = value.portalName;
        this.portalLink = value.portalLink;
    }

    public Portal(
            Integer portalId,
            String portalName,
            String portalLink
    ) {
        this.portalId = portalId;
        this.portalName = portalName;
        this.portalLink = portalLink;
    }

    public Integer getPortalId() {
        return this.portalId;
    }

    public void setPortalId(Integer portalId) {
        this.portalId = portalId;
    }

    public String getPortalName() {
        return this.portalName;
    }

    public void setPortalName(String portalName) {
        this.portalName = portalName;
    }

    public String getPortalLink() {
        return this.portalLink;
    }

    public void setPortalLink(String portalLink) {
        this.portalLink = portalLink;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Portal (");

        sb.append(portalId);
        sb.append(", ").append(portalName);
        sb.append(", ").append(portalLink);

        sb.append(")");
        return sb.toString();
    }
}
