/*
 * This file is generated by jOOQ.
 */
package cn.edu.nju.teamwiki.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Portal implements Serializable {

    private static final long serialVersionUID = 1003114783;

    private Integer portalId;
    private String  portalName;
    private String  portalLink;
    private String  portalIcon;

    public Portal() {}

    public Portal(Portal value) {
        this.portalId = value.portalId;
        this.portalName = value.portalName;
        this.portalLink = value.portalLink;
        this.portalIcon = value.portalIcon;
    }

    public Portal(
        Integer portalId,
        String  portalName,
        String  portalLink,
        String  portalIcon
    ) {
        this.portalId = portalId;
        this.portalName = portalName;
        this.portalLink = portalLink;
        this.portalIcon = portalIcon;
    }

    public Integer getPortalId() {
        return this.portalId;
    }

    public void setPortalId(Integer portalId) {
        this.portalId = portalId;
    }

    public String getPortalName() {
        return this.portalName;
    }

    public void setPortalName(String portalName) {
        this.portalName = portalName;
    }

    public String getPortalLink() {
        return this.portalLink;
    }

    public void setPortalLink(String portalLink) {
        this.portalLink = portalLink;
    }

    public String getPortalIcon() {
        return this.portalIcon;
    }

    public void setPortalIcon(String portalIcon) {
        this.portalIcon = portalIcon;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Portal (");

        sb.append(portalId);
        sb.append(", ").append(portalName);
        sb.append(", ").append(portalLink);
        sb.append(", ").append(portalIcon);

        sb.append(")");
        return sb.toString();
    }
}
