/*
 * This file is generated by jOOQ.
 */
package cn.edu.nju.teamwiki.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Share implements Serializable {

    private static final long serialVersionUID = -2137982758;

    private Integer       shareId;
    private String        shareTitle;
    private String        shareContent;
    private Integer       shareUser;
    private LocalDateTime shareTime;

    public Share() {}

    public Share(Share value) {
        this.shareId = value.shareId;
        this.shareTitle = value.shareTitle;
        this.shareContent = value.shareContent;
        this.shareUser = value.shareUser;
        this.shareTime = value.shareTime;
    }

    public Share(
        Integer       shareId,
        String        shareTitle,
        String        shareContent,
        Integer       shareUser,
        LocalDateTime shareTime
    ) {
        this.shareId = shareId;
        this.shareTitle = shareTitle;
        this.shareContent = shareContent;
        this.shareUser = shareUser;
        this.shareTime = shareTime;
    }

    public Integer getShareId() {
        return this.shareId;
    }

    public void setShareId(Integer shareId) {
        this.shareId = shareId;
    }

    public String getShareTitle() {
        return this.shareTitle;
    }

    public void setShareTitle(String shareTitle) {
        this.shareTitle = shareTitle;
    }

    public String getShareContent() {
        return this.shareContent;
    }

    public void setShareContent(String shareContent) {
        this.shareContent = shareContent;
    }

    public Integer getShareUser() {
        return this.shareUser;
    }

    public void setShareUser(Integer shareUser) {
        this.shareUser = shareUser;
    }

    public LocalDateTime getShareTime() {
        return this.shareTime;
    }

    public void setShareTime(LocalDateTime shareTime) {
        this.shareTime = shareTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Share (");

        sb.append(shareId);
        sb.append(", ").append(shareTitle);
        sb.append(", ").append(shareContent);
        sb.append(", ").append(shareUser);
        sb.append(", ").append(shareTime);

        sb.append(")");
        return sb.toString();
    }
}
