/*
 * This file is generated by jOOQ.
 */
package cn.edu.nju.teamwiki.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Source implements Serializable {

    private static final long serialVersionUID = 635938473;

    private Integer sourceType;
    private String  sourceName;

    public Source() {}

    public Source(Source value) {
        this.sourceType = value.sourceType;
        this.sourceName = value.sourceName;
    }

    public Source(
        Integer sourceType,
        String  sourceName
    ) {
        this.sourceType = sourceType;
        this.sourceName = sourceName;
    }

    public Integer getSourceType() {
        return this.sourceType;
    }

    public void setSourceType(Integer sourceType) {
        this.sourceType = sourceType;
    }

    public String getSourceName() {
        return this.sourceName;
    }

    public void setSourceName(String sourceName) {
        this.sourceName = sourceName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Source (");

        sb.append(sourceType);
        sb.append(", ").append(sourceName);

        sb.append(")");
        return sb.toString();
    }
}
