#!/usr/bin/env groovy

pipeline {
    agent any
    tools {
        maven 'maven3'
        jdk 'jdk8'
        'org.jenkinsci.plugins.docker.commons.tools.DockerTool' 'docker'
    }
//    options {
//        skipStagesAfterUnstable()
//    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -Ptest -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -Ptest test'
            }
        }
        stage('SonarQube') {
            steps {
                sh 'mvn sonar:sonar -Dsonar.host.url=http://sonarqube:9000'
            }
        }
        stage('Deploy') {
            steps {
                sh 'chmod 777 ./jenkins/scripts/deploy.sh'
                sh './jenkins/scripts/deploy.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh 'chmod 777 ./jenkins/scripts/deliver.sh'
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}